// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTbI8zypqtudN-qg49pgXjFEUTxeUxRY',
    appId: '1:496658259861:web:1e78da432045e50e0b609c',
    messagingSenderId: '496658259861',
    projectId: 'quranlearnerbd',
    authDomain: 'quranlearnerbd.firebaseapp.com',
    storageBucket: 'quranlearnerbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZQLtmv2LNw-5LupO1FQBtbeO1okiiew',
    appId: '1:496658259861:android:79cffeea631e2c950b609c',
    messagingSenderId: '496658259861',
    projectId: 'quranlearnerbd',
    storageBucket: 'quranlearnerbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7_UqnIdIvGDaEPxHbYXx6fP31b_FJsxE',
    appId: '1:496658259861:ios:65d536e3eaab5a1b0b609c',
    messagingSenderId: '496658259861',
    projectId: 'quranlearnerbd',
    storageBucket: 'quranlearnerbd.appspot.com',
    iosClientId: '496658259861-f4gcak81vfjsgkt719i7kc6b9fpjssq7.apps.googleusercontent.com',
    iosBundleId: 'com.sofolit.quranlearner',
  );
}
